-- ============================================================
-- GlobalBank DB — T001: Create GLOBAL_USER on ATP1
-- Run as ADMIN on bankdb_high
-- ============================================================

-- Create schema user
CREATE USER GLOBAL_USER IDENTIFIED BY "SecurePass123!";

-- Basic connection + object creation
GRANT CONNECT, RESOURCE TO GLOBAL_USER;
GRANT CREATE TABLE       TO GLOBAL_USER;
GRANT CREATE VIEW        TO GLOBAL_USER;
GRANT CREATE SEQUENCE    TO GLOBAL_USER;
GRANT CREATE TRIGGER     TO GLOBAL_USER;
GRANT CREATE PROCEDURE   TO GLOBAL_USER;
GRANT CREATE DATABASE LINK TO GLOBAL_USER;
GRANT UNLIMITED TABLESPACE TO GLOBAL_USER;

-- Required for DBMS_CLOUD_ADMIN.CREATE_DATABASE_LINK
GRANT EXECUTE ON DBMS_CLOUD_ADMIN TO GLOBAL_USER;
GRANT EXECUTE ON DBMS_CLOUD       TO GLOBAL_USER;

-- Required by DBMS_CLOUD_ADMIN.CREATE_DATABASE_LINK internally
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO GLOBAL_USER;

COMMIT;

SELECT 'GLOBAL_USER created OK' AS status FROM DUAL;
