-- ============================================================
-- GlobalBank DB — T009-T014: Central Node Schema
-- Run as GLOBAL_USER on bankdb_high
-- ============================================================

-- Drop existing objects (idempotent)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PLATI_RATE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CREDITE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_ACCES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENTI_PROFIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIPURI_CONT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUCURSALE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENT_GLOBAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CREDIT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLATA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- T009: SUCURSALE + seed 2 rows
CREATE TABLE SUCURSALE (
    ID_Sucursala  NUMBER(4)     PRIMARY KEY,
    Nume          VARCHAR2(100) NOT NULL,
    Oras          VARCHAR2(50)  NOT NULL,
    Adresa        VARCHAR2(200) NOT NULL,
    CONSTRAINT chk_sucursala_oras CHECK (Oras IN ('Bucuresti', 'Cluj'))
);

INSERT INTO SUCURSALE VALUES (1, 'GlobalBank Bucuresti Centru', 'Bucuresti', 'Bulevardul Unirii 10, Sector 4');
INSERT INTO SUCURSALE VALUES (2, 'GlobalBank Cluj Napoca',      'Cluj',      'Strada Memorandumului 5, Cluj-Napoca');

-- T010: TIPURI_CONT master + seed 4 rows (replicated to Bucharest/Cluj slaves via trigger)
CREATE TABLE TIPURI_CONT (
    ID_Tip    NUMBER(4)    PRIMARY KEY,
    Denumire  VARCHAR2(50) NOT NULL UNIQUE,
    Dobanda   NUMBER(5,2)  NOT NULL,
    CONSTRAINT chk_dobanda CHECK (Dobanda >= 0 AND Dobanda <= 100)
);

INSERT INTO TIPURI_CONT VALUES (1, 'Curent',   0.00);
INSERT INTO TIPURI_CONT VALUES (2, 'Economii', 3.50);
INSERT INTO TIPURI_CONT VALUES (3, 'Depozit',  5.00);
INSERT INTO TIPURI_CONT VALUES (4, 'Credit',  15.00);

-- T011: CLIENTI_PROFIL (vertical fragment — profile data) + global sequence
-- SEQ_CLIENT_GLOBAL used by INSTEAD OF trigger on CLIENTI_GLOBAL view
CREATE SEQUENCE SEQ_CLIENT_GLOBAL START WITH 2000001 MAXVALUE 9999999 NOCACHE NOCYCLE;

CREATE TABLE CLIENTI_PROFIL (
    ID_Client    NUMBER(10)    PRIMARY KEY,
    Email        VARCHAR2(150) UNIQUE,
    Telefon      VARCHAR2(15),
    Scor_Credit  NUMBER(3)     DEFAULT 500,
    CONSTRAINT chk_scor  CHECK (Scor_Credit BETWEEN 0 AND 999),
    CONSTRAINT chk_email CHECK (Email LIKE '%@%.%')
);

-- T012: CREDITE (cross-node FK to CLIENTI enforced by trigger, not DDL)
CREATE SEQUENCE SEQ_CREDIT START WITH 2000001 MAXVALUE 9999999 NOCACHE NOCYCLE;

CREATE TABLE CREDITE (
    ID_Credit    NUMBER(10)   PRIMARY KEY,
    Suma_Totala  NUMBER(15,2) NOT NULL,
    Rata_Lunara  NUMBER(10,2) NOT NULL,
    ID_Client    NUMBER(10)   NOT NULL,
    CONSTRAINT chk_credit_suma CHECK (Suma_Totala > 0),
    CONSTRAINT chk_credit_rata CHECK (Rata_Lunara > 0)
);

-- T013: PLATI_RATE
CREATE SEQUENCE SEQ_PLATA START WITH 2000001 MAXVALUE 9999999 NOCACHE NOCYCLE;

CREATE TABLE PLATI_RATE (
    ID_Plata    NUMBER(10)   PRIMARY KEY,
    Data_Plata  DATE         DEFAULT SYSDATE NOT NULL,
    Suma        NUMBER(10,2) NOT NULL,
    ID_Credit   NUMBER(10)   NOT NULL,
    CONSTRAINT chk_plata_suma  CHECK (Suma > 0),
    CONSTRAINT fk_plata_credit FOREIGN KEY (ID_Credit) REFERENCES CREDITE(ID_Credit)
);

-- T014: LOG_ACCES
CREATE SEQUENCE SEQ_LOG START WITH 1 MAXVALUE 99999999 NOCACHE NOCYCLE;

CREATE TABLE LOG_ACCES (
    ID_Log     NUMBER(10)    PRIMARY KEY,
    Utilizator VARCHAR2(50)  NOT NULL,
    Data_Ora   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    Actiune    VARCHAR2(200) NOT NULL
);

COMMIT;

SELECT 'Central schema created OK' AS status FROM DUAL;
